// src/features/proyectos/lib/proyectosMock.ts
import { Project } from '../types';

export const projectMock: Project[] = [
  {
    proyecto_id: 1,
    codigo: "PROY-2026-CH01",
    acronimo: "TOROMOCHO",
    fecha_de_inicio: "2026-01-15",
    fecha_finalizacion: "2028-12-31",
    pagina_web: "https://chinalco.com.pe",
    mandato: true,
    uri: "https://api.observatorio.com/proyectos/1",
    tipo: "Minería",
    categoria: "Nacional",
    estado: "En Construcción"
  },
  {
    proyecto_id: 2,
    codigo: "PROY-2026-EN02",
    acronimo: "RUBI-II",
    fecha_de_inicio: "2025-05-10",
    fecha_finalizacion: "2027-06-30", 
    pagina_web: "https://enel.com",
    mandato: false,
    uri: "https://api.observatorio.com/proyectos/2",
    tipo: "Electricidad",
    categoria: "Sectorial",
    estado: "Factibilidad"
  },
  {
    proyecto_id: 3,
    codigo: "PROY-2026-PT03",
    acronimo: "LOTE-95",
    fecha_de_inicio: "2024-02-20",
    fecha_finalizacion: "2029-11-15",
    pagina_web: "https://petrotal.com",
    mandato: true,
    uri: "https://api.observatorio.com/proyectos/3",
    tipo: "Hidrocarburos",
    categoria: "Regional",
    estado: "En Operación"
  },
  {
    proyecto_id: 4,
    codigo: "PROY-2026-ZF04",
    acronimo: null, 
    fecha_de_inicio: "2026-03-01",
    fecha_finalizacion: "2028-05-20",
    pagina_web: "https://zafranal.com.pe",
    mandato: false,
    uri: "https://api.observatorio.com/proyectos/4",
    tipo: "Minería",
    categoria: "Provincial",
    estado: "Evaluación"
  },
  {
    proyecto_id: 5,
    codigo: "PROY-2026-QY05",
    acronimo: "QUELLAVECO",
    fecha_de_inicio: "2023-08-12",
    fecha_finalizacion: "2027-12-01",
    pagina_web: "https://angloamerican.com",
    mandato: true,
    uri: "https://api.observatorio.com/proyectos/5",
    tipo: "Minería",
    categoria: "Nacional",
    estado: "En Operación"
  },
  {
    proyecto_id: 6,
    codigo: "PROY-2026-CH06",
    acronimo: "CHAGLLA",
    fecha_de_inicio: "2025-11-01",
    fecha_finalizacion: "2029-04-15",
    pagina_web: null,
    mandato: false,
    uri: "https://api.observatorio.com/proyectos/6",
    tipo: "Electricidad",
    categoria: "Regional",
    estado: "En Construcción"
  },
  {
    proyecto_id: 7,
    codigo: "PROY-2026-CM07",
    acronimo: "CAMISEA LOTE 88",
    fecha_de_inicio: "2024-06-20",
    fecha_finalizacion: "2032-10-10",
    pagina_web: "https://pluspetrol.com.pe",
    mandato: true,
    uri: "https://api.observatorio.com/proyectos/7",
    tipo: "Hidrocarburos",
    categoria: "Nacional",
    estado: "En Operación"
  },
  {
    proyecto_id: 8,
    codigo: "PROY-2026-AM08",
    acronimo: "ANTAMINA EXP",
    fecha_de_inicio: "2026-02-10",
    fecha_finalizacion: "2030-06-30",
    pagina_web: "https://antamina.com",
    mandato: false,
    uri: "https://api.observatorio.com/proyectos/8",
    tipo: "Minería",
    categoria: "Regional",
    estado: "Factibilidad"
  },
  {
    proyecto_id: 9,
    codigo: "PROY-2026-MA09",
    acronimo: "MANTARO REV",
    fecha_de_inicio: "2025-01-20",
    fecha_finalizacion: "2028-03-15",
    pagina_web: "https://electroperu.com.pe",
    mandato: true,
    uri: "https://api.observatorio.com/proyectos/9",
    tipo: "Electricidad",
    categoria: "Nacional",
    estado: "Evaluación"
  },
  {
    proyecto_id: 10,
    codigo: "PROY-2026-TA10",
    acronimo: "TALARA MOD",
    fecha_de_inicio: "2023-05-15",
    fecha_finalizacion: "2027-01-31",
    pagina_web: "https://petroperu.com.pe",
    mandato: false,
    uri: "https://api.observatorio.com/proyectos/10",
    tipo: "Hidrocarburos",
    categoria: "Sectorial",
    estado: "En Construcción"
  },
  {
    proyecto_id: 11,
    codigo: "PROY-2026-BA11",
    acronimo: "BAYOVAR III",
    fecha_de_inicio: "2026-04-05",
    fecha_finalizacion: "2029-08-25",
    pagina_web: null,
    mandato: false,
    uri: "https://api.observatorio.com/proyectos/11",
    tipo: "Minería",
    categoria: "Provincial",
    estado: "Factibilidad"
  },
  {
    proyecto_id: 12,
    codigo: "PROY-2026-SA12",
    acronimo: "SAN GABAN III",
    fecha_de_inicio: "2024-09-18",
    fecha_finalizacion: "2027-11-30",
    pagina_web: "https://sangaban.com.pe",
    mandato: true,
    uri: "https://api.observatorio.com/proyectos/12",
    tipo: "Electricidad",
    categoria: "Regional",
    estado: "En Construcción"
  },
  // --- FIN DE LA PÁGINA 1 (ÍTEM 12) ---
  // --- INICIO DE LA PÁGINA 2 (ÍTEM 13) ---
  {
    proyecto_id: 13,
    codigo: "PROY-2026-LP13",
    acronimo: "LAS BAMBAS",
    fecha_de_inicio: "2024-01-11",
    fecha_finalizacion: "2029-12-31",
    pagina_web: "https://mmg.com",
    mandato: true,
    uri: "https://api.observatorio.com/proyectos/13",
    tipo: "Minería",
    categoria: "Nacional",
    estado: "En Operación"
  },
  {
    proyecto_id: 14,
    codigo: "PROY-2026-CO14",
    acronimo: "CORANI",
    fecha_de_inicio: "2026-05-12",
    fecha_finalizacion: "2029-06-20",
    pagina_web: "https://bearcreekmining.com",
    mandato: false,
    uri: "https://api.observatorio.com/proyectos/14",
    tipo: "Minería",
    categoria: "Provincial",
    estado: "Factibilidad"
  },
  {
    proyecto_id: 15,
    codigo: "PROY-2026-MO15",
    acronimo: "MOQUEGUA SOLAR",
    fecha_de_inicio: "2025-07-14",
    fecha_finalizacion: "2027-04-18",
    pagina_web: null,
    mandato: false,
    uri: "https://api.observatorio.com/proyectos/15",
    tipo: "Electricidad",
    categoria: "Regional",
    estado: "En Construcción"
  },
  {
    proyecto_id: 16,
    codigo: "PROY-2026-AG16",
    acronimo: "AGUAYTIA EXP",
    fecha_de_inicio: "2025-03-22",
    fecha_finalizacion: "2028-10-05",
    pagina_web: "https://aguaytia.com.pe",
    mandato: true,
    uri: "https://api.observatorio.com/proyectos/16",
    tipo: "Hidrocarburos",
    categoria: "Sectorial",
    estado: "Evaluación"
  },
  {
    proyecto_id: 17,
    codigo: "PROY-2026-TI17",
    acronimo: "TIA MARIA",
    fecha_de_inicio: "2026-02-01",
    fecha_finalizacion: "2030-05-15",
    pagina_web: "https://southerperu.com",
    mandato: false,
    uri: "https://api.observatorio.com/proyectos/17",
    tipo: "Minería",
    categoria: "Nacional",
    estado: "Evaluación"
  },
  {
    proyecto_id: 18,
    codigo: "PROY-2026-IN18",
    acronimo: "INAMBARI CTRL",
    fecha_de_inicio: "2024-10-10",
    fecha_finalizacion: "2029-01-20",
    pagina_web: null,
    mandato: true,
    uri: "https://api.observatorio.com/proyectos/18",
    tipo: "Electricidad",
    categoria: "Regional",
    estado: "Factibilidad"
  },
  {
    proyecto_id: 19,
    codigo: "PROY-2026-LO19",
    acronimo: null,
    fecha_de_inicio: "2025-08-05",
    fecha_finalizacion: "2028-11-12",
    pagina_web: "https://perupetro.com.pe",
    mandato: false,
    uri: "https://api.observatorio.com/proyectos/19",
    tipo: "Hidrocarburos",
    categoria: "Provincial",
    estado: "En Construcción"
  },
  {
    proyecto_id: 20,
    codigo: "PROY-2026-CE20",
    acronimo: "CERRO VERDE V",
    fecha_de_inicio: "2023-12-01",
    fecha_finalizacion: "2027-09-30",
    pagina_web: "https://fcx.com",
    mandato: true,
    uri: "https://api.observatorio.com/proyectos/20",
    tipo: "Minería",
    categoria: "Nacional",
    estado: "En Operación"
  },
  {
    proyecto_id: 21,
    codigo: "PROY-2026-HU21",
    acronimo: "HUALLAGA ENER",
    fecha_de_inicio: "2026-01-10",
    fecha_finalizacion: "2028-07-25",
    pagina_web: null,
    mandato: false,
    uri: "https://api.observatorio.com/proyectos/21",
    tipo: "Electricidad",
    categoria: "Regional",
    estado: "Factibilidad"
  },
  {
    proyecto_id: 22,
    codigo: "PROY-2026-PA22",
    acronimo: "PAGORENI 56",
    fecha_de_inicio: "2025-02-14",
    fecha_finalizacion: "2029-03-18",
    pagina_web: "https://repsol.pe",
    mandato: true,
    uri: "https://api.observatorio.com/proyectos/22",
    tipo: "Hidrocarburos",
    categoria: "Sectorial",
    estado: "En Construcción"
  },
  {
    proyecto_id: 23,
    codigo: "PROY-2026-MI23",
    acronimo: "MICHIQUILLAY",
    fecha_de_inicio: "2026-04-20",
    fecha_finalizacion: "2031-12-15",
    pagina_web: "https://southernperu.com.pe",
    mandato: false,
    uri: "https://api.observatorio.com/proyectos/23",
    tipo: "Minería",
    categoria: "Regional",
    estado: "Evaluación"
  },
  {
    proyecto_id: 24,
    codigo: "PROY-2026-WI24",
    acronimo: "WIND PERU",
    fecha_de_inicio: "2025-09-01",
    fecha_finalizacion: "2027-05-30",
    pagina_web: "https://engie.com.pe",
    mandato: false,
    uri: "https://api.observatorio.com/proyectos/24",
    tipo: "Electricidad",
    categoria: "Nacional",
    estado: "En Operación"
  }
];